#!/usr/bin/env python3

from PIL import Image

# Load the image
image = Image.open("./assets/pastiche_8x8.png").convert("RGBA")  # Use RGBA to handle transparency
width, height = image.size
pixels = image.load()

CHAR_W = 8
CHAR_H = 8


def print_char(cx, cy):
    print("{")
    for py in range(CHAR_H):
        num = 0;
        offset = 1;
        for px in range(CHAR_H):
            x = px + cx * CHAR_W
            y = py + cy * CHAR_H
            r, g, b, a = pixels[x, y]
            if a > 125:
                num += offset
            offset *= 2
        print("\t0b{:08b},".format(num))
    print("},")


print("// THIS FILE IS AUTOGENERATED")
print(f"#include <stdint.h>")
print()
print(f"const uint8_t font_bitmap[{int(height / CHAR_H)} * {int(width / CHAR_W)}][8] = {{")
for cy in range(int(height / CHAR_H)):
    for cx in range(int(width / CHAR_W)):
        print_char(cx, cy)

print("};")
